version: "3"

services:
  postgres:
    image: postgres:15.2-alpine3.17
    ports:
      - "5432:5432"
    volumes:
      - ./db_data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: newsletter

  newsletter:
    image: ghcr.io/kunalsin9h/newsletter:latest
    ports:
      - "5000:5000"
    environment:
      APP_APPLICATION__PORT: 5000
      APP_APPLICATION__HOST: "0.0.0.0"
      APP_DATABASE__REQUIRE_SSL: false
      APP_DATABASE__DATABASE_NAME: newsletter
      APP_DATABASE__USERNAME: postgres
      APP_DATABASE__PASSWORD: password
      APP_DATABASE__HOST: postgres
      APP_DATABASE__PORT: 5432
      APP_EMAIL_CLIENT__BASE_URL: "api.email@cm.cm"
      APP_EMAIL_CLIENT__SENDER_EMAIL: "xyz"
      APP_EMAIL_CLIENT_AUTHORIZATION_TOKEN: "token"
