version: "3"

services:
  postgres:
    image: postgres:15.2-alpine3.17
    ports:
      - "5432:5432"
    volumes:
      - ./db_data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: newsletter

  redis:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - "6379:6379"

  newsletter:
    image: ghcr.io/kunalsin9h/newsletter:latest
    ports:
      - "5000:5000"
    volumes:
      - ./production.yaml/:/newsletter/configuration/production.yaml
