redis_uri: "redis://127.0.0.1:6379"

application:
  host: "127.0.0.1"
  base_url: "http://127.0.0.1"
  hmac_secret: "aGF2ZSBhIHNlY3JldCB3aGljaCBpcyBtb3JlIHRoZW4gMjAgY2hhcmFjdGVycyBsb25nLCBpIGhvcGUgdGhpcyBpcyBnb29kIGluIGxlbmdodAo="

database:
  host: "localhost"
  username: "postgres"
  password: "password"
  require_ssl: false

email_client:
  base_url: "https://api.postmarkapp.com/email"
  sender_email: "newsletter@your-domain.com"
  authorization_token: "-------------postmark-app-token-----------------"
  timeout_millisecond: 10000
