redis_uri: "redis://127.0.0.1:6379"

application:
  host: "127.0.0.1"
  base_url: "http://127.0.0.1"
  hmac_secret: "aGF2ZSBhIHNlY3JldCB3aGljaCBpcyBtb3JlIHRoZW4gMjAgY2hhcmFjdGVycyBsb25nLCBpIGhvcGUgdGhpcyBpcyBnb29kIGluIGxlbmdodAo="

database:
  host: "localhost"
  username: "postgres"
  password: "password"
  require_ssl: false

email_client:
  base_url: "https://api.postmarkapp.com/email"
  sender_email: "newsletter@kunalsin9h.com"
  authorization_token: "6aae038d-3e9e-4a65-9231-183e125e5b8a"
  timeout_millisecond: 10000
