application:
  host: "0.0.0.0"
  base_url: "https://newsletter.kunalsin9h.com"

database:
  require_ssl: true

email_client:
  base_url: "prod"
  sender_email: "prod@gmail.com"
  authorization_token: "6aae038d"
