name: Build

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup 
        if: github.ref != 'refs/heads/master'
        uses: actions/checkout@v3
      - name: Run Build
        if: github.ref != 'refs/heads/master'
        run: cargo build

