name: CI
run-name: "CI: ${{ github.event.pull_request.title || 'on master' }}"

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - '**'


env:
  CARGO_TERM_COLOR: always
  SQLX_VERSION: 0.6.2
  SQLX_FEATURES: "rustls, postgres"

jobs:
  test:
    name: Test run with cargo test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.2-alpine3.17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: newsletter
        ports:
          - 5432
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          key: sqlx-${{ env.SQLX_VERSION }}
      - name: Install sqlx-cli
        run:
          cargo install sqlx-cli
            --version=${{ env.SQLX_VERSION }}
            --features=${{ env.SQLX_FEATURES }}
            --no-default-features
            --locked
      - name: Install postgresql-client
        run: sudo apt-get update && sudo apt-get install postgresql-client -y
      - name: Migrate database
        run: SKIP_DOCKER=true ./scripts/init_db.sh
      - name: Run Test
        run: cargo test

  format:
    name: Formatting check with rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: cargo fmt -- --check
        run: cargo fmt -- --check

  lint:
    name: Linting check with clippy
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.2-alpine3.17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: newsletter
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          key: sqlx-${{ env.SQLX_VERSION }}
      - name: Install sqlx-cli
        run:
          cargo install sqlx-cli
            --version=${{ env.SQLX_VERSION }}
            --features=${{ env.SQLX_FEATURES }}
            --no-default-features
            --locked
      - name: Install postgresql-client
        run: sudo apt-get update && sudo apt-get install postgresql-client -y
      - name: Migrate database
        run: SKIP_DOCKER=true ./scripts/init_db.sh
      - name: Rust Lint
        run: cargo clippy -- -D warnings

  # coverage:
  #   name: Code coverage check with cargo-tarpaulin
  #   runs-on: ubuntu-latest
  #   container:
  #     image: xd009642/tarpaulin
  #     options: --security-opt seccomp=unconfined
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: Swatinem/rust-cache@v2
  #     - name: Generate code coverage
  #       run: cargo tarpaulin --verbose --workspace
