name: Code Coverage
run-name: "Code Coverage @ ${{ github.event.pull_request.title }}"

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  coverage:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Repository
        if: github.ref != 'refs/heads/master'
        uses: actions/checkout@v3
      - name: Install Tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Run code coverage
        if: github.ref != 'refs/heads/master'
        run: cargo tarpaulin
