name: Code Coverage

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  coverage:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup
        if: github.ref != 'refs/heads/master'
        uses: actions/checkout@v3
        run: cargo install cargo-tarpaulin
      - name: Run code coverage
        if: github.ref != 'refs/heads/master'
        run: cargo tarpaulin
