name: Format
run-name: "Format @ ${{ github.event.pull_request.title }}"

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  format:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup
        if: github.ref != 'refs/heads/master'
        uses: actions/checkout@v3
      - name: Run Format
        if: github.ref != 'refs/heads/master'
        run: cargo fmt -- --check
