name: Lint

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup
        if: github.ref != 'refs/heads/master'
        uses: actions/checkout@v3
      - name: Run Lint
        if: github.ref != 'refs/heads/master'
        run: cargo clippy -- -D warning
