name: Security Audit
run-name: "Security Audit: ${{ github.event.pull_request.title || github.event.push.title }}"

on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
    - cron: 0 0 * * *    # Every day at 12:00 AM

jobs:
  security_audit:
    name: Security audit check with cargo-audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@cargo-deny
      - name: cargo deny check advisories
        run: cargo deny check advisories
