name: Security Vulnerability
run-name: "Auditing @ ${{ github.event.pull_request.title }}"

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  audit:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup
        if: github.ref != 'refs/heads/master'
        uses: actions/checkout@v3
      - name: Install cargo audit
        run: cargo install cargo-audit
      - name: Run security check
        if: github.ref != 'refs/heads/master'
        run: cargo audit
