name: Tests
run-name: "Testing @ ${{ github.event.pull_request.title }}"

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup 
        if: github.ref != 'refs/heads/master'
        uses: actions/checkout@v3
      - name: Run Test
        if: github.ref != 'refs/heads/master'
        run: cargo test

